spring:
  session:
    redis:
      flush-mode: on_save
  application:
    name: 'cloud-file-storage'
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/001-create-users-table.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

minio:
  server:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123


