spring:
  session:
    redis:
      flush-mode: on_save
  application:
    name: 'cloud-file-storage'
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

