spring:
  session:
    redis:
      flush-mode: on_save
  application:
    name: 'cloud-file-storage'
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB

minio:
  server:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123


